# Naive Bayes

In [50]:
import pandas as pd
#import scikit-learn dataset library
from sklearn import datasets
#load dataset
wine=datasets.load_wine()
wine
#this data set is the resultof a chemical analysis
#of wines set is the same region in Italy
#but analysis determined the quantities of 13 constituents found in each of 

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [51]:
print(wine.data)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [52]:
print(wine.target)
#print(wine.target_names)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [53]:
#import train_test _split function
from sklearn.model_selection import train_test_split
#split dataset into training set and test set
X_train,X_test,y_train,y_test=train_test_split(wine.data,wine.target,test_size=0.3,random_state=15)

In [54]:
#import gaussian naive baye model
from sklearn.naive_bayes import GaussianNB

#Create a gaussian classifier
gnb=GaussianNB()

#Train the model using the training sets
gnb.fit(X_train,y_train)
#predict the response for test dataset
y_pred=gnb.predict(X_test)
y_pred

array([2, 0, 2, 0, 1, 0, 1, 2, 1, 0, 1, 1, 1, 1, 0, 1, 2, 0, 2, 1, 2, 0,
       2, 2, 2, 0, 2, 1, 0, 1, 1, 2, 0, 1, 2, 0, 0, 1, 1, 2, 1, 1, 2, 2,
       1, 1, 2, 0, 0, 0, 0, 2, 0, 1])

In [55]:
#import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model A, how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test,y_pred))
print("CM",metrics.confusion_matrix(y_test,y_pred))
#accuracy_score(y_test,y_pred)
#c=confusion_matrix(y_test,y_pred)


Accuracy: 0.9814814814814815
CM [[17  1  0]
 [ 0 19  0]
 [ 0  0 17]]


 # K Nearest Neighbour 

In [58]:
import numpy as np
import pandas as pd
data=pd.read_csv('T-shirt.csv')
data

Height(in cms)  Weight(in kgs) T-shirt size
0              158              58            M
1              158              59            M
2              158              63            M
3              160              59            M
4              160              60            M
5              163              60            M
6              163              61            M
7              160              64            L
8              163              64            L
9              165              61            L
10             165              62            L
11             165              65            L
12             168              62            L
13             168              63            L
14             168              66            L
15             170              63            L
16             170              64            L
17             170              68            L

In [59]:
x=(161-data['Height(in cms)'])**2+(61-data['Weight(in kgs)'])**2
x

0      18
1      13
2      13
3       5
4       2
5       5
6       4
7      10
8      13
9      16
10     17
11     32
12     50
13     53
14     74
15     85
16     90
17    130
dtype: int64

In [60]:
data['distance']=np.sqrt(x)

In [61]:
data

Height(in cms)  Weight(in kgs) T-shirt size   distance
0              158              58            M   4.242641
1              158              59            M   3.605551
2              158              63            M   3.605551
3              160              59            M   2.236068
4              160              60            M   1.414214
5              163              60            M   2.236068
6              163              61            M   2.000000
7              160              64            L   3.162278
8              163              64            L   3.605551
9              165              61            L   4.000000
10             165              62            L   4.123106
11             165              65            L   5.656854
12             168              62            L   7.071068
13             168              63            L   7.280110
14             168              66            L   8.602325
15             170              63            L   9.219544
16             170              64            L   9.486833
17             170              68            L  11.401754

In [63]:
data.columns

Index(['Height(in cms)', 'Weight(in kgs)', 'T-shirt size', 'distance'], dtype='object')

In [83]:
X=data[['Height(in cms)','Weight(in kgs)']]
X

Height(in cms)  Weight(in kgs)
0              158              58
1              158              59
2              158              63
3              160              59
4              160              60
5              163              60
6              163              61
7              160              64
8              163              64
9              165              61
10             165              62
11             165              65
12             168              62
13             168              63
14             168              66
15             170              63
16             170              64
17             170              68

In [84]:
y=data[['T-shirt size']]
y

T-shirt size
0             M
1             M
2             M
3             M
4             M
5             M
6             M
7             L
8             L
9             L
10            L
11            L
12            L
13            L
14            L
15            L
16            L
17            L

In [85]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
Y=labelencoder_y.fit_transform(y)
print(Y)

[1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [86]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=15)

In [88]:
#import knearest neighbors classifier model 
from sklearn.neighbors import KNeighborsClassifier
#create KNN Classifier
knn=KNeighborsClassifier(n_neighbors=5)
# Train the model using the training sets
knn.fit(X_train,y_train)
#predict the response for test dataset
y_pred=knn.predict(X_test)

#import scikit-learn metrics module for accuracy calculation
from sklearn import metrics
#Model Accuracy, how often is the classifier correct?
print("Accuracy",metrics.accuracy_score(y_test,y_pred))

Accuracy 1.0


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


In [27]:
import numpy as np
import pandas as pd
bird=pd.read_csv('bird.csv')
#bd
bird.head()

id   huml  humw  ulnal  ulnaw   feml  femw   tibl  tibw   tarl  tarw type
0   0  80.78  6.68  72.01   4.88  41.81  3.70   5.50  4.03  38.70  3.84   SW
1   1  88.91  6.63  80.53   5.59  47.04  4.30  80.22  4.51  41.50  4.01   SW
2   2  79.97  6.37  69.26   5.28  43.07  3.90  75.35  4.04  38.31  3.34   SW
3   3  77.65  5.70  65.76   4.77  40.04  3.52  69.17  3.40  35.78  3.41   SW
4   4  62.80  4.84  52.09   3.73  33.95  2.72  56.27  2.96  31.88  3.13   SW

In [30]:
#bd.columns
#bd.replace(to_replace=['huml', 'humw', 'ulnal', 'ulnaw', 'feml', 'femw', 'tibl', 'tibw',
      # 'tarl', 'tarw'],value=0)
bird=bird.replace(to_replace=np.nan,value=0)

In [45]:
bird.isna().sum()

id       0
huml     0
humw     0
ulnal    0
ulnaw    0
feml     0
femw     0
tibl     0
tibw     0
tarl     0
tarw     0
type     0
dtype: int64

In [48]:
X=bird.iloc[:,1:11].values
Y=bird.iloc[:,11:].values
#X,Y

In [44]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.4,random_state=10)
X_train,Y_train

(array([[150.  ,   8.05, 170.  , ...,   5.76,  78.41,   4.33],
        [ 20.08,   2.07,  25.78, ...,   1.35,  30.25,   1.09],
        [ 41.19,   3.78,  43.24, ...,   2.99,  46.74,   2.54],
        ...,
        [140.59,   6.59, 115.97, ...,   7.83,  74.86,   3.52],
        [ 30.99,   2.09,  26.14, ...,   1.98,  30.8 ,   1.95],
        [ 44.47,   4.24,  55.77, ...,   2.82,  18.57,   3.6 ]]), array([['W'],
        ['SO'],
        ['SO'],
        ['SO'],
        ['SW'],
        ['SO'],
        ['T'],
        ['SW'],
        ['SO'],
        ['SW'],
        ['SO'],
        ['SW'],
        ['W'],
        ['W'],
        ['SW'],
        ['P'],
        ['SW'],
        ['W'],
        ['SW'],
        ['SO'],
        ['SO'],
        ['P'],
        ['W'],
        ['SW'],
        ['SO'],
        ['SO'],
        ['R'],
        ['R'],
        ['W'],
        ['W'],
        ['SO'],
        ['SW'],
        ['SO'],
        ['SW'],
        ['SW'],
        ['P'],
        ['R'],
        ['SO'],
        ['SW']

In [50]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,Y_train)
y_pred=knn.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [52]:
from sklearn import metrics
metrics.accuracy_score(Y_test,y_pred)

0.7380952380952381

In [53]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(X_train,Y_train)
rfc_predict=rfc.predict(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [54]:
from sklearn import metrics
metrics.accuracy_score(Y_test,rfc_predict)

0.7857142857142857