In [2]:
def addition(**a):
    print(type(a))
    for key,value in a.items():
        print(key,value)
addition(name='sana',sub='python')

<class 'dict'>
name sana
sub python


In [6]:
def addition(a, *b):
    print(b)
    
    for i in b:
        a+=i
    print(a)
    
addition(1,2,3,4)

(2, 3, 4)
10


In [9]:
def addition(**a): # **a=dictionary  *a=tuple
    print(type(a))
    for i,j in a.items():
        print(i,j)
    
addition(name='sana',sub='python')

<class 'dict'>
name sana
sub python


In [12]:
import keyword
print(keyword.kwlist,end='')

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']

In [5]:
try:
    a=int(input())
    b=5
    c=a+b
    #print(c)
    
except ValueError:
    a=int(input())
    b=5
    c=a+b
    print(c)
    
except TypeError:
    a=int(input())
    b=5
    c=a+b
    print(c)
    
else:
    z=11
    h=22
    j=h/z
    print(j)
finally:
    e=7
    f=8
    g=e*f
    print(g)

5
2.0
56


In [1]:
import datetime
d=datetime.datetime.now()
d.day

21

In [2]:
d.year

2019

In [5]:
d.minute

54

In [6]:
d.hour

9

In [8]:
d.second

57

In [11]:
dir(datetime)

['MAXYEAR',
 'MINYEAR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'date',
 'datetime',
 'datetime_CAPI',
 'sys',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

In [14]:
d.weekday()

3

In [15]:
import datetime as dt

In [16]:
d.microsecond

632444

In [17]:
dir(dt)

['MAXYEAR',
 'MINYEAR',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'date',
 'datetime',
 'datetime_CAPI',
 'sys',
 'time',
 'timedelta',
 'timezone',
 'tzinfo']

In [19]:
import calendar as cl

In [27]:
print(cl.month(2019,11))

   November 2019
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30



In [28]:
cal=cl.month(2019,8)
print(cal)

    August 2019
Mo Tu We Th Fr Sa Su
          1  2  3  4
 5  6  7  8  9 10 11
12 13 14 15 16 17 18
19 20 21 22 23 24 25
26 27 28 29 30 31



In [31]:
print(cl.weekday(2019,11,5))

1


In [30]:
print(cl.monthrange(2019,11)) # 4 weeks and 30 days

(4, 30)


In [37]:
dir(cl)

['Calendar',
 'EPOCH',
 'FRIDAY',
 'February',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'January',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MONDAY',
 'SATURDAY',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_spacing',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthlen',
 'monthrange',
 'nextmonth',
 'prcal',
 'prevmonth',
 'prmonth',
 'prweek',
 'repeat',
 'setfirstweekday',
 'sys',
 'timegm',
 'week',
 'weekday',
 'weekheader']

In [45]:
print (cl.calendar(2020))

                                  2020

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                         1
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       2  3  4  5  6  7  8
13 14 15 16 17 18 19      10 11 12 13 14 15 16       9 10 11 12 13 14 15
20 21 22 23 24 25 26      17 18 19 20 21 22 23      16 17 18 19 20 21 22
27 28 29 30 31            24 25 26 27 28 29         23 24 25 26 27 28 29
                                                    30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                   1  2  3       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       4  5  6  7  8  9 10       8  9 10 11 12 13 14
13 14 15 16 17 18 19      11 12 13 14 15 16 17      15 16 17 18 19 20 21
20 21 22 23 24 25 26      18 19 20 21 22 

In [50]:
cl.leapdays(2019,2030)

3

In [51]:
cl.isleap(2019)

False

In [52]:
import time
localtime=time.localtime(time.time())

In [60]:
from datetime import date
today=date.today()
today

datetime.date(2019, 11, 21)

In [61]:
d.today()

datetime.datetime(2019, 11, 21, 10, 38, 0, 122478)

In [64]:
d1=today.strftime("%d %b %y")
d1

'21 Nov 19'

In [67]:
td=today.strftime("%d %B %y")
td

'21 November 19'

In [68]:
today.strftime("%d %m %y")

'21 11 19'

In [ ]:
from tkinter import *
tk=Tk()
canvas=Canvas(tk,width=400,height=400)
canvas.pack()
canvas.create_arc(10,10,200,100,extent=180,style=ARC)
tk.mainloop()

In [1]:
import numpy as np
x=np.random.randn(2,3)
print(x)

[[-1.21200606 -1.48507485 -0.00739771]
 [ 0.14031992  0.07589744  1.32803305]]


In [2]:
x*10

array([[-12.1200606 , -14.85074848,  -0.07397708],
       [  1.40319922,   0.75897441,  13.28033046]])

In [3]:
x+x

array([[-2.42401212, -2.9701497 , -0.01479542],
       [ 0.28063984,  0.15179488,  2.65606609]])

In [4]:
x-x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
y=np.array([[1,2,3],[6,7,8]])
y

array([[1, 2, 3],
       [6, 7, 8]])

In [33]:
#y.ndim
y.shape

(2, 3)

In [6]:
y*y

array([[ 1,  4,  9],
       [36, 49, 64]])

In [7]:
y-y

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
1/y

array([[1.        , 0.5       , 0.33333333],
       [0.16666667, 0.14285714, 0.125     ]])

In [9]:
y**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.44948974, 2.64575131, 2.82842712]])

In [10]:
z=np.array([[1,2,3],[4,5,6]])
z

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
z>y

array([[False, False, False],
       [False, False, False]])

In [12]:
ar=np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
ar[5]

5

In [16]:
ar[5:8]

array([5, 6, 7])

In [20]:
ar[5:7]=12
ar

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [23]:
ar[0]=10
ar

array([10,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [34]:
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
array_2d.shape

(3, 3)

In [36]:
array_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
array_2d 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
print(array_2d[0])
print(array_2d[1])
print(array_2d[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [44]:
print(array_2d[0:2])

[[1 2 3]
 [4 5 6]]


In [47]:
print(array_2d[0:2,0:2])

[[1 2]
 [4 5]]


In [48]:
print(array_2d[0:2,1:2])

[[2]
 [5]]


In [37]:
# multiple slicing
array_2d[0:2,1:] 

array([[2, 3],
       [5, 6]])

In [39]:
array_2d[1,0:2]

array([4, 5])

In [70]:
data=np.random.randn(7,4)
data

array([[-1.05403979, -0.54862849, -0.22916033, -0.51760508],
       [ 1.73024642,  0.26253745, -1.32707485,  0.20671154],
       [-0.47856551,  0.19549486,  0.70968719, -0.73485868],
       [ 0.22892744,  2.14003297,  0.44183064, -2.08028454],
       [-1.12297842, -0.41465123, -0.84020902,  1.25858907],
       [ 0.11004696,  0.63927616,  0.02570875,  1.37736833],
       [ 1.3881252 , -0.22842884,  0.62272895,  2.41833736]])

In [77]:
names=np.array(['bob','joe','will','bob','will','joe','joe'])
names=='bob'


array([ True, False, False,  True, False, False, False])

In [78]:
data[names=='bob']  

array([[-1.05403979, -0.54862849, -0.22916033, -0.51760508],
       [ 0.22892744,  2.14003297,  0.44183064, -2.08028454]])

In [83]:
data[names=='bob',2:]

array([[-0.22916033, -0.51760508],
       [ 0.44183064, -2.08028454]])

In [84]:
data[names=='bob',3:]

array([[-0.51760508],
       [-2.08028454]])

In [85]:
mask=(names=='bob')|(names=='will')
mask

array([ True, False,  True,  True,  True, False, False])

In [109]:
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [86]:
data[mask]

array([[-1.05403979, -0.54862849, -0.22916033, -0.51760508],
       [-0.47856551,  0.19549486,  0.70968719, -0.73485868],
       [ 0.22892744,  2.14003297,  0.44183064, -2.08028454],
       [-1.12297842, -0.41465123, -0.84020902,  1.25858907]])

In [87]:
data[data<0]=0
data

array([[0.        , 0.        , 0.        , 0.        ],
       [1.73024642, 0.26253745, 0.        , 0.20671154],
       [0.        , 0.19549486, 0.70968719, 0.        ],
       [0.22892744, 2.14003297, 0.44183064, 0.        ],
       [0.        , 0.        , 0.        , 1.25858907],
       [0.11004696, 0.63927616, 0.02570875, 1.37736833],
       [1.3881252 , 0.        , 0.62272895, 2.41833736]])

In [88]:
data[names!='joe']=7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [1.73024642, 0.26253745, 0.        , 0.20671154],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.11004696, 0.63927616, 0.02570875, 1.37736833],
       [1.3881252 , 0.        , 0.62272895, 2.41833736]])

In [116]:
a=np.empty((8,4))
for i in range(8):
    a[i]=i
print(a)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [117]:
a

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [120]:
a[[0,2,4,6]] # it takes a index positions of a

array([[0., 0., 0., 0.],
       [2., 2., 2., 2.],
       [4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [121]:
a[[-1,-3,-5]] # it takes the reversing index values of a

array([[7., 7., 7., 7.],
       [5., 5., 5., 5.],
       [3., 3., 3., 3.]])

In [94]:
a=np.arange(32).reshape((8,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [127]:
a[[1,5,7,2],[0,3,1,2]] # need explanation


array([1., 5., 7., 2.])

In [128]:
a[[1,5,7,2]][:,[0,3,1,2]]

array([[1., 1., 1., 1.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.],
       [2., 2., 2., 2.]])

In [132]:
np.dot(a.T,a)

array([[140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.],
       [140., 140., 140., 140.]])

In [103]:
a=np.arange(16).reshape((2,2,4)) # 2rows 2col 4 elements
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [104]:
a.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [105]:
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [106]:
a.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

## PANDAS
- Series
- DataFrames

In [133]:
import pandas as pd
p1=pd.Series([4,7,-5,3]) # convert series in a given list
p1

0    4
1    7
2   -5
3    3
dtype: int64

In [135]:
p1=pd.Series([4,7,-5,3],index=['a','b','c','d'])
p1

a    4
b    7
c   -5
d    3
dtype: int64

In [137]:
print(p1.index)
print(p1.values)

Index(['a', 'b', 'c', 'd'], dtype='object')
[ 4  7 -5  3]


In [141]:
p1['b']

7

In [144]:
p1[['a','c']]

a    4
c   -5
dtype: int64

In [147]:
s={'sana':50,"sudha":100,"ashok":150,"suresh":200}
pd.Series(s)


sana       50
sudha     100
ashok     150
suresh    200
dtype: int64

In [151]:
states=['sana','poojitha','swamy','raja']
x=pd.Series(s,index=states)  # in above s sana:50 remining all NaN
x

sana        50.0
poojitha     NaN
swamy        NaN
raja         NaN
dtype: float64

In [152]:
x+x

sana        100.0
poojitha      NaN
swamy         NaN
raja          NaN
dtype: float64